### ISSUE TITLE
Please I need help. No module named 'llava'

### ISSUE THREAD

**Issue by Hany1978** [magic-quill/MagicQuill#33]
I m using Windows and I really tried everything to solve this problem with no success

Traceback (most recent call last):
  File "D:\MagicQuill\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "D:\MagicQuill\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'

This is one of the best AI apps ever made!!!! and I m really want to use it, So is there anything to do in order to solve this issue?

**Comment by zliucz** [comment]
Hi, I'm sorry to see this coming... Did you get llava1.2.2.post1 correctly install? Maybe you can show me the log when installing the llava1.2.2.post1. We'll see what we can help.

**Comment by Hany1978** [comment]
I m really don't know what do you men by installion of llava1.2.2.post1 I simply followed the instructions on Windows but have this error. Are you going to release another version specified for Windows to be easy to install?

**Comment by zliucz** [comment]
I assume some thing error here during your installation at this step:
'''
cp -f pyproject.toml MagicQuill/LLaVA/
pip install -e MagicQuill/LLaVA/
'''

We have already prepared a Windows machine for testing, and plan to update our code and tutorial within this week for more stable and convenient installation. Meanwhile, you may find this [guide](https://github.com/magic-quill/MagicQuill/issues/11#issuecomment-2489276625) helpful.

**Comment by jgardet** [comment]
Could I have the same issue (Windows as well)?

File "C:\Users\XXX\anaconda3\lib\site-packages\llava\__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (C:\Users\XXX\anaconda3\lib\site-packages\llava\model\__init__.py)

=> it doesn't take the installed LLava but search it elsewhere

This:
'''
cp -f pyproject.toml MagicQuill/LLaVA/
pip install -e MagicQuill/LLaVA/
'''
Worked correctly, although it might be installing this in the wrong place.
Has anyone succeeded to make it work in windows?

**Comment by jgardet** [comment]
The windows install script linked above worked. Thanks to the author.

**Comment by JasonHuangChina** [comment]
Same problem in Ubuntu 20.04, follow the instructions

**Comment by zliucz** [comment]
For those who didn't install llava correctly. We have update the instructions and tutorial for convenient install in [README.md](https://github.com/magic-quill/MagicQuill/blob/main/README.md). Try to re-install the llava again.

**Comment by Yu-0001** [comment]
I also encountered this problem and it was solved when I changed the name of the MagicQuill folder to English.

**Comment by bews** [comment]
For those who get the same problem on windows: 

Turns out git clone doesn't clone included [LLaVA](https://github.com/haotian-liu/LLaVA) repository, leaving MagicQuill\MagicQuill\LLaVA directory empty. This why even tho it does install it without any errors, it still doesn't work.
The solution is to manually download the included repo https://github.com/haotian-liu/LLaVA/tree/c121f0432da27facab705978f83c4ada465e46fd as zip and unzip the contents to MagicQuill\MagicQuill\LLaVA directory.

**Comment by ganiket25201001** [comment]
> Could I have the same issue (Windows as well)?
> 
> File "C:\Users\XXX\anaconda3\lib\site-packages\llava__init__.py", line 1, in from .model import LlavaLlamaForCausalLM ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (C:\Users\XXX\anaconda3\lib\site-packages\llava\model__init__.py)
> 
> => it doesn't take the installed LLava but search it elsewhere
> 
> This: ''' cp -f pyproject.toml MagicQuill/LLaVA/ pip install -e MagicQuill/LLaVA/ ''' Worked correctly, although it might be installing this in the wrong place. Has anyone succeeded to make it work in windows?

its not working for me can you help 

(MagicQuill) C:\Users\User1\Desktop\MQ\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "C:\Users\ganik\Desktop\MQ\MagicQuill\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "C:\Users\ganik\Desktop\MQ\MagicQuill\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'
